[package]
name = "jky-apps"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
reqwest.workspace = true
futures-util.workspace = true
base64 = "0.21"
quick-xml = "0.41"
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true }
